#!/bin/bash

opt-3.3 -print-callgraph $1 2> /home/klee/T631Project/proj-skeleton/input 1>/dev/null
java -cp "/home/klee/T631Project/proj-skeleton" Bugs /home/klee/T631Project/proj-skeleton/input $2 $3
