

import java.util.HashMap;
import java.util.ArrayList;
import java.util.Arrays;
import java.io.File;
import java.util.Scanner;

class test {
	public static void main(String[] args) {
		

		//get the callgraph generated by opt
		String input = readFromFile("input");
		
		//hashmap that contains our functions and their uses
		HashMap<String, Integer> functions = new HashMap<String, Integer>();
		
		//split our input into lines
		String[] lines = input.split("\n");
		

		for(String line : lines) {
			String[] words = line.split(" ");
			String last = words[words.length -1];

			if(last.startsWith("#") && !(line.contains("null"))) {
				int calls = Character.getNumericValue(last.charAt(last.length()-1));
				String func = line.split("'")[1];
				functions.put(func, calls);
			}
		}

		System.out.print(Arrays.asList(functions));
		
	}

	public static String readFromFile(String filepath) {
		
			String result = "";
			try {
				File file = new File(filepath);
				Scanner input = new Scanner(file);

				while(input.hasNextLine()){
					String line = input.nextLine() + "\n";
					result += line;
				}
				input.close();
			} catch(Exception ex) {
				ex.printStackTrace();
			}

			return result;
	}
}